name       : python-kiwisolver
version    : 1.0.1
release    : 2
source     :
    - https://github.com/nucleic/kiwi/archive/1.0.1.tar.gz : 8e7fc64fea6d3af96aed63391d35bbbd292a429c8e463277dac839b735503a28
license    : BSD-3-Clause
component  : programming.python
summary    : An efficient C++ implementation of the Cassowary constraint solving algorithm
description: |
    Kiwi is an implementation of the algorithm based on the seminal Cassowary paper. It is not a refactoring of the original C++ solver. Kiwi has been designed from the ground up to be lightweight and fast. Kiwi ranges from 10x to 500x faster than the original Cassowary solver with typical use cases gaining a 40x improvement. Memory savings are consistently > 5x.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
