name       : python-kiwisolver
version    : 1.3.1
release    : 3
source     :
    - https://github.com/nucleic/kiwi/archive/1.3.1.tar.gz : 91d56ec628be2513a02c3721d4d8173416daf37c49423fe7a41a0e30c1101269
homepage   : https://github.com/nucleic/kiwi
license    : BSD-3-Clause
component  : programming.python
summary    : An efficient C++ implementation of the Cassowary constraint solving algorithm
description: |
    Kiwi is an implementation of the algorithm based on the seminal Cassowary paper. It is not a refactoring of the original C++ solver. Kiwi has been designed from the ground up to be lightweight and fast. Kiwi ranges from 10x to 500x faster than the original Cassowary solver with typical use cases gaining a 40x improvement. Memory savings are consistently > 5x.
builddeps  :
    - pkgconfig(python3)
    - python-cppy
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
