name       : python-kiwisolver
version    : 1.4.1
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/k/kiwisolver/kiwisolver-1.4.1.tar.gz : 91bfcd2a14bea6f93c86876c4abccb53dc3f0bcad55e3a0af0b3e57ced6eef11
homepage   : https://github.com/nucleic/kiwi
license    : BSD-3-Clause
component  : programming.python
summary    : An efficient C++ implementation of the Cassowary constraint solving algorithm
description: |
    Kiwi is an implementation of the algorithm based on the seminal Cassowary paper. It is not a refactoring of the original C++ solver. Kiwi has been designed from the ground up to be lightweight and fast. Kiwi ranges from 10x to 500x faster than the original Cassowary solver with typical use cases gaining a 40x improvement. Memory savings are consistently > 5x.
builddeps  :
    - pkgconfig(python3)
    - python-cppy
    - python-pytest
    - python-setuptools-scm
    - python-wheel
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
