name       : python-kiwisolver
version    : 1.4.4
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/k/kiwisolver/kiwisolver-1.4.4.tar.gz : d41997519fcba4a1e46eb4a2fe31bc12f0ff957b2b81bac28db24744f333e955
homepage   : https://github.com/nucleic/kiwi
license    : BSD-3-Clause
component  : programming.python
summary    : An efficient C++ implementation of the Cassowary constraint solving algorithm
description: |
    Kiwi is an implementation of the algorithm based on the seminal Cassowary paper. It is not a refactoring of the original C++ solver. Kiwi has been designed from the ground up to be lightweight and fast. Kiwi ranges from 10x to 500x faster than the original Cassowary solver with typical use cases gaining a 40x improvement. Memory savings are consistently > 5x.
builddeps  :
    - pkgconfig(python3)
    - python-cppy
    - python-pytest
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
